apiVersion: v1
kind: Service
metadata:
  name: {{ include "qbittorrent.fullname" . }}-webui
  labels:
    {{- include "qbittorrent.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.webui.type }}
  ports:
    - port: {{ .Values.service.webui.port }}
      targetPort: 8080
      nodePort: {{ .Values.service.webui.nodePort }}
      protocol: TCP
      name: webui
  selector:
    {{- include "qbittorrent.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "qbittorrent.fullname" . }}-torrent
  labels:
    {{- include "qbittorrent.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.torrent.type }}
  ports:
    - port: {{ .Values.service.torrent.port }}
      targetPort: 6881
      nodePort: {{ .Values.service.torrent.nodePort }}
      protocol: TCP
      name: torrent-tcp
    - port: {{ .Values.service.torrent.port }}
      targetPort: 6881
      nodePort: {{ .Values.service.torrent.nodePort }}
      protocol: UDP
      name: torrent-udp
  selector:
    {{- include "qbittorrent.selectorLabels" . | nindent 4 }}
