apiVersion: v2
name: plex
description: Plex Media Server with hardware transcoding
type: application
version: 1.0.0
appVersion: "1.43.0"
maintainers:
  - name: muchiny
    url: https://github.com/muchiny
