replicaCount: 1
image:
  repository: lscr.io/linuxserver/qbittorrent
  tag: "5.1.4"
  pullPolicy: IfNotPresent
initContainer:
  image:
    repository: busybox
    tag: "1.36"
service:
  webui:
    type: NodePort
    port: 8080
    nodePort: 30080
  torrent:
    type: NodePort
    port: 6881
    nodePort: 30881
persistence:
  config:
    hostPath: /home/muchini/media-data/config/qbittorrent
    mountPath: /config
  downloads:
    hostPath: /home/muchini/media-data/torrents
    mountPath: /downloads
  media:
    hostPath: /media
    mountPath: /media
environment:
  PUID: "1000"
  PGID: "1000"
  TZ: Europe/Paris
  WEBUI_PORT: "8080"
dns:
  dnsProxyService: dnscrypt-proxy
resources:
  limits:
    memory: 1Gi
    cpu: 1000m
  requests:
    memory: 256Mi
    cpu: 100m
priorityClassName: media-high
nodeSelector:
  kubernetes.io/arch: arm64
networkPolicy:
  enabled: true
