apiVersion: v1
kind: Service
metadata:
  name: {{ include "dnscrypt-proxy.fullname" . }}
  labels:
    {{- include "dnscrypt-proxy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- if .Values.service.clusterIP }}
  clusterIP: {{ .Values.service.clusterIP }}
  {{- end }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5053
      protocol: UDP
      name: dns-udp
    - port: {{ .Values.service.port }}
      targetPort: 5053
      protocol: TCP
      name: dns-tcp
  selector:
    {{- include "dnscrypt-proxy.selectorLabels" . | nindent 4 }}
