replicaCount: 1
image:
  repository: klutchell/dnscrypt-proxy
  tag: "2.1.5"
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 5053
  clusterIP: 10.43.48.123
resources:
  limits:
    memory: 64Mi
    cpu: 100m
  requests:
    memory: 32Mi
    cpu: 50m
config:
  # Use Cloudflare DoH
  serverNames:
    - cloudflare
  listenAddresses:
    - "0.0.0.0:5053"
  maxClients: 250
  ipv6Servers: false
  dnscrypt: false
  doh: true
  cache: true
  cacheSize: 4096
  cacheMinTTL: 2400
  cacheMaxTTL: 86400
priorityClassName: media-critical
nodeSelector:
  kubernetes.io/arch: arm64
networkPolicy:
  enabled: true
