apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cloudflared.fullname" . }}
  labels:
    {{- include "cloudflared.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "cloudflared.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "cloudflared.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: cloudflared
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - proxy-dns
            - --port
            - "5053"
            - --address
            - "0.0.0.0"
            {{- range .Values.dns.upstreams }}
            - --upstream
            - {{ . | quote }}
            {{- end }}
          ports:
            - containerPort: 5053
              protocol: UDP
              name: dns-udp
            - containerPort: 5053
              protocol: TCP
              name: dns-tcp
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          livenessProbe:
            tcpSocket:
              port: 5053
            initialDelaySeconds: 10
            periodSeconds: 30
