apiVersion: v1
kind: Service
metadata:
  name: {{ include "cloudflared.fullname" . }}
  labels:
    {{- include "cloudflared.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  clusterIP: {{ .Values.service.clusterIP | default "" | quote }}
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 300
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5053
      protocol: UDP
      name: dns-udp
    - port: {{ .Values.service.port }}
      targetPort: 5053
      protocol: TCP
      name: dns-tcp
  selector:
    {{- include "cloudflared.selectorLabels" . | nindent 4 }}
